version: "3.9"

services:
  tarantool:
    image: tarantool/tarantool:3.0.1
    container_name: tarantool
    volumes:
      - ./utils/tarantool:/opt/tarantool/app
      - ./data:/var/lib/tarantool
    environment:
      - TT_APP_NAME=app
      - TT_INSTANCE_NAME=instance001
      - TT_USERNAME=${TARANTOOL_USER}
      - TT_PASSWORD=${TARANTOOL_PASSWORD}
    ports:
      - "3301:3301"
    networks:
      - dev-network

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      # timezone inside container
      - TZ

      # necessary Postgres options/variables
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - dev-network

  mattermost:
    depends_on:
      - postgres
    image: mattermost/mattermost-enterprise-edition:9.11.6
    container_name: mattermost
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH}:/mattermost/bleve-indexes:rw
    environment:
      - TZ

      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE

      - MM_BLEVESETTINGS_INDEXDIR

      - MM_SERVICESETTINGS_SITEURL
    ports:
      - ${APP_PORT}:8065
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp
    networks:
      - dev-network

  votingbot:
    container_name: votingbot
    build: ./
    command: ./votingbot
    restart: always
    environment:
      - BOT_MM_TEAM
      - BOT_MM_TOKEN
      - BOT_MM_CHANNEL
      - BOT_MM_SERVER
      - BOT_MM_USERNAME
      
      - BOT_TT_ADDRES
      - BOT_TT_USERNAME
      - BOT_TT_PASSWORD
    ports:
      - 8000:8000
    depends_on: 
      - tarantool
      - mattermost
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge