version: "3.9"

services:
  tarantool:
    image: tarantool/tarantool:3.0.1
    container_name: tarantool
    volumes:
      - ./utils/tarantool:/opt/tarantool/app
      - ./data:/var/lib/tarantool
    environment:
      - TT_APP_NAME=app
      - TT_INSTANCE_NAME=instance001
      - TT_USERNAME=${TARANTOOL_USER}
      - TT_PASSWORD=${TARANTOOL_PASSWORD}
    ports:
      - "3301:3301"
    networks:
      - dev-network

  votingbot:
    container_name: votingbot
    build: ./
    command: ./votingbot
    restart: always
    environment:
      - BOT_MM_TEAM
      - BOT_MM_TOKEN
      - BOT_MM_CHANNEL
      - BOT_MM_SERVER
      - BOT_MM_USERNAME
      
      - BOT_TT_ADDRES
      - BOT_TT_USERNAME
      - BOT_TT_PASSWORD
    ports:
      - 8000:8000
    depends_on: 
      - tarantool
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge